---
- name: Configure scaling governor
  ansible.builtin.include_tasks:
    file: present.ansible.yml
  when: cpu_scaling_governor_state | lower == "present"

- name: Remove scaling governor configuration
  ansible.builtin.include_tasks:
    file: absent.ansible.yml
  when: cpu_scaling_governor_state | lower == "absent"
