- name: Create scaling-governor service file
  become: true
  ansible.builtin.template:
    src: templates/scaling-governor.service.j2
    dest: /etc/systemd/system/scaling-governor.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart scaling-governor

- name: Enable scaling-governor
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: scaling-governor.service
