---
- name: Read available scaling governors
  ansible.builtin.slurp:
    path: /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
  register: cpu_scaling_governor_available_raw

- name: Fail when scaling governor is not available
  ansible.builtin.debug:
    msg: "{{ 'The specified cpu scaling governor (' + cpu_scaling_governor
      + ') is not available on this system. Available governors are: '
      + cpu_scaling_governor_available_list | join(', ') + '.' }}"
  failed_when: true
  when: cpu_scaling_governor not in cpu_scaling_governor_available_list

- name: Ensure scaling-governor service exists
  become: true
  ansible.builtin.template:
    src: templates/scaling-governor.service.j2
    dest: "{{ cpu_scaling_governor_service_file_location }}"
    owner: root
    group: root
    mode: '0644'
  notify: Start scaling-governor service

- name: Ensure scaling-governor service is running and enabled
  become: true
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    name: "{{ cpu_scaling_governor_service_name }}"
