---
- name: Reload daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start scaling-governor service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: "{{ cpu_scaling_governor_service_name }}"
    state: started
