---
- name: Reload daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart scaling-governor service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: scaling-governor.service
    state: restarted
