---
- name: Test cpu_scaling_governor_service_folder_used
  ansible.builtin.assert:
    that: cpu_scaling_governor_service_folder_used == test_item.output
    fail_msg: >-
      {{ 'Test: ' + test_item.name + ', Expected: ' + test_item.output | string
      + ' , but got: ' + cpu_scaling_governor_service_folder_used | string }}
  loop:
    - name: no trailing slash
      output: /etc/systemd/system
      input: /etc/systemd/system
    - name: has trailing slash
      output: /etc/systemd/system
      input: /etc/systemd/system/
  loop_control:
    loop_var: test_item
  vars:
    cpu_scaling_governor_service_folder: "{{ test_item.input }}"
  ignore_errors: "{{ cpu_scaling_governor_ci_ignore }}"
